comparers:
  - changed-files:
      - any-glob-to-any-file:
          - comparers.go
          - comparers_test.go

slices:
  - changed-files:
      - any-glob-to-any-file:
          - slices.go
          - slices_test.go

strings:
  - changed-files:
      - any-glob-to-any-file:
          - strings.go
          - strings_test.go

errors:
  - changed-files:
      - any-glob-to-any-file:
          - errors.go
          - errors_test.go

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/*
          - .github/**/*
          - .golangci.yml
