language: go

dist: focal

os:
  - linux

services:
  - docker

before_install:
  - git config --global url."git@github.com:".insteadOf "https://github.com/"
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0

go:
  - 1.14.x
  - 1.15.x

script:
  - make ci_tests

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
