name: Continues Integration

on:
  push:
    branches:
    - master
    - feature/*
    - bugfix/*
  pull_request:
    branches:
    - master
    - feature/*
    - bugfix/*

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Golangci
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1


    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Linting Code
      run: make lint

    - name: Running Tests
      run: make ci_tests
